name: logger_io
description: "Simple logger. Does what a logger should do: send your input messages to a series of outputs; and nothing more."
version: 1.0.1
repository: https://github.com/cedvdb/logger_io

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  ansicolor: ^2.0.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
