name: perf
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  logger_io:
    path: ../
  logger: 2.0.2+1
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
